version: 2

models:
  - name: session_summary
    description: "Analytics model for session data"
    columns:
      - name: sessionid
        description: "trying some tests"
        data_tests:
          - unique
          - not_null